name: Deploy to Railway

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (if any)
      run: |
        # 这里可以添加测试命令
        python -c "import enhanced_final_app; print('App import successful')"

    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: railway-app/railway-deploy@v1
      with:
        railway-token: ${{ secrets.RAILWAY_TOKEN }}
        service: ${{ secrets.RAILWAY_SERVICE_ID }}
        
    - name: Health Check
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        # 等待部署完成后进行健康检查
        sleep 30
        curl -f ${{ secrets.RAILWAY_APP_URL }}/api/health || exit 1
